## abre en http://localhost:8080/swagger-ui/index.html
spring.application.name=ecommerce
spring.profiles.active=dev
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=${JWT_SECRET}
